export const pt_br = {
  subtitulo: 'AprenderÉDivertido',
  pesquisa: 'Pesquisar',
  linguagens: 'linguagens',
  matematica: 'matemática',
  ciencias: 'ciências',
  humanas: 'humanas',
  lp: 'Letras',
  arte: 'Arte',
  quantidade: 'Quantidade',
  formasGeometricas: 'Formas Geométricas',
  corpoHumano: 'Corpo Humano',
  natureza: 'Natureza',
  geografia: 'Geografia',
  historia: 'História',
  jogoCorpoHumanoDescricao: 'Vamos identificar as partes do corpo',
  jogoCorpoHumanoDica: 'Arrastar as partes para a posição correta',
  jogoAcessoriosDescricao: 'Vamos adicionar os acessórios',
  jogoAcessoriosDica: 'Arrastar as peças para a posição correta',
  jogoQuantidadesDescricao: 'Vamos marcar quantos temos',
  jogoQuantidadesDica: 'Clicar nos quadrados para representar a quantidade',
  jogoCoracoesDescricao: 'Vamos contar corações',
  jogoCoracoesDica: 'Clicar na quantidade certa de corações',
  jogoIniciaisDescricao: 'Vamos completar a palavra',
  jogoIniciaisDica: 'Clicar na letra que está faltando',
  jogoQtdeFormasDescricao: 'Vamos contar as formas',
  jogoQtdeFormasDica: 'Arrastar as formas até sua quantidade',
  jogoAlfabetoDescricao: 'Vamos colocar as maçãs na árvore',
  jogoAlfabetoDica: 'Arrastar as letras para completar o alfabeto',
  rankingAvatar: 'Avatar',
  rankingNome: 'Nome',
  rankingPontos: 'Pontos',
  rankingNivel: 'Nível',
  jogoEncaixarFormasDescricao: 'Vamos encaixar as formas',
  jogoEncaixarFormasDica: 'Arrastar as formas até suas sombras',
  jogoCoresFrutasDescricao: 'Vamos ligar as frutas e suas cores',
  jogoCoresFrutasDica: 'Arrastar as cores até as frutas',
  jogoAnimaisDescricao: 'Vamos ligar cada animal ao seu alimento',
  jogoAnimaisDica: 'Arrastar os animais até os alimentos',
  jogoVeiculosDescricao: 'Vamos ligar cada veículo ao seu meio de transporte',
  jogoVeiculosDica: 'Arrastar os veículos até os lugares',
  jogoPlanetasDescricao: 'Vamos identificar os nomes',
  jogoPlanetasDica: 'Arrastar os nomes até seu correspondente',
  jogoCoresDescricao: 'Vamos identificar os nomes das cores',
  jogoCoresDica: 'Clicar na letra que falta',
  jogoSeresVivosDescricao: 'Vamos identificar os nomes dos seres vivos',
  jogoSeresVivosDica: 'Clicar na letra que falta',
  jogoFolcloreDescricao: 'Vamos identificar os personagens do folclore brasileiro',
  jogoFolcloreDica: 'Clicar na letra que falta',
  jogoOndeEstaoDescricao: 'Vamos identificar onde eles estão',
  jogoOndeEstaoDica: 'Arrastar ao lugar correto',
  escolhaUmTema: 'Escolha um tema',
  tooltipSave: 'Carregar Jogo',
  tooltipPlay: 'Iniciar Novo Jogo',
}